version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: inquiry_demo_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inquiry_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    build:
      context: ./InquiryDemoProject
      dockerfile: ./InquiryAPI/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8001:80"

  status_updater:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    build:
      context: ./InquiryDemoProject
      dockerfile: ./InquiryStatusUpdater/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8002:80"

  angular_app:
    build:
      context: ./FrontEnd/inquiry-demo-app
      dockerfile: ./Dockerfile
    ports:
      - "4201:80"

  nginx:
    container_name: nginx-local
    image: nginx:latest
    ports:
      - "4202:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - inquiry_api
      - status_updater
      - angular_app

volumes:
  postgres_data:
