version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: inquiry_demo_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
